<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitca471655429108e8ec829e47f16dd596
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitca471655429108e8ec829e47f16dd596::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitca471655429108e8ec829e47f16dd596::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
